openapi: 3.0.2
info:
  title: UTM API (USS->DSS and USS->USS)
  version: 1.0.0
  description: >-
    Interface definitions for communication between a UAS Service Supplier (USS)
    and a Discovery and Synchronization Service (DSS), as well as for
    communication between two USSs.

    DSS functionality includes identification of peer UTM USS instances
    (managing flight operational intents and constraints). USS functionality
    includes sharing details of flight operational intents and constraints.

    Note: Unless otherwise specified, fields specified in a message but not
    declared in the API must be ignored.

    Whenever a object-type field may be omitted, it may also be set to null for
    the same effect.
security:
- Authority:
  - utm.strategic_coordination
  - utm.constraint_management
  - utm.constraint_processing
  - utm.conformance_monitoring_sa
  - utm.availability_arbitration
tags:
- name: Operational intent references
  description: >-
    Endpoints exposed by the DSS for interaction with references to
    operational intents.
- name: Operational intent details
  description: >-
    Endpoints exposed by USSs for interaction with details of operational
    intents.
- name: Constraint references
  description: >-
    Endpoints exposed by the DSS for interaction with references to
    constraints.
- name: Constraint details
  description: >-
    Endpoints exposed by USSs for interaction with details of constraints.
- name: Subscriptions
  description: >-
    Endpoints exposed by the DSS for interaction with subscription entities.
- name: Reports
  description: Endpoints exposed by the DSS for reporting peer DSS issues.
- name: Availability
  description: Endpoints exposed by the DSS for declaring USS availability.
- name: Logging
  description: >-
    Pseudo-endpoints not intended to be implemented literally, but rather to
    illustrate logging data formats
- name: dss
  description: Endpoints exposed by the DSS server.
- name: p2p_utm
  description: Endpoints exposed by UTM USSs for peer-peer communication.